name: Coverage
on:
  push:
    branches: [ master ]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.coverage-deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'
      - name: Generate coverage output
        run: |
          ./gradlew :koverHtmlReport
          echo "COVERAGE=$(./gradlew -q :printLineCoverage)" >> $GITHUB_ENV
      - name: Configure Pages
        uses: actions/configure-pages@v3
      - name: Upload coverage artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/reports/kover/html
      - name: Deploy coverage report
        id: coverage-deployment
        uses: actions/deploy-pages@v2
      - name: Update coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: d911211e98e25a98f2fa644c9526d062
          filename: click-track-coverage-badge.json
          label: Coverage
          message: ${{ env.COVERAGE }}%
          valColorRange: ${{ env.COVERAGE }}
          minColorRange: 0
          maxColorRange: 100
