name: deploy
on:
  workflow_dispatch:
jobs:
  deploy-google-play:
    name: Deploy to Google Play
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: ./gradlew -s :android-app:bundleRelease :android-app:uploadCrashlyticsSymbolFileRelease
      - uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: android-app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.GPC_KEYSTORE }}
          alias: ${{ secrets.GPC_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.GPC_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.GPC_KEY_PASSWORD }}
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GPC_SERVICE_ACCOUNT_JSON }}
          packageName: com.vsevolodganin.clicktrack
          releaseFiles: ${{ steps.sign_app.outputs.signedReleaseFile }}
          track: internal
          status: draft
